In [ ]:
!pip install -q pyomo

In [ ]:
from pyomo.environ import * 

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

Given that Saga Logistics is to transport electic vehicles from warehouses to markets.There are 8 warehouses and we are to transport EVs to 8 markets.
Let we define variables such that $ x_{i,j} $ where $ x_{i,j} $ denotes the number of electic vehicles transported to $ j^{th} \text{market from } \ i^{th} $  warehouse.

Since  market  has demand to be fulfilled  so sum of each quantity what is supplied to 1st market by all the warehouses must be equal to the demand of that market so for 1st market  : 


$ \sum_{i=1}^8 x_{i,1} = 250 \\
 similarly: \\ \sum_{i=1}^8 x_{i,2} = 300 \\  \sum_{i=1}^8 x_{i,3} = 425 \\  \sum_{i=1}^8 x_{i,4} =270 \\  \sum_{i=1}^8 x_{i,5} = 375  \\  \sum_{i=1}^8 x_{i,6} = 225 \\  \sum_{i=1}^8 x_{i,7} = 185 \\  \sum_{i=1}^8 x_{i,8} = 110 \\ $ 

 Since we are given that each warehouse has its availability stock so all the supplied stock must be less than or equal to the available stock in that warehouse so for first market: 

 $ \sum_{i=1}^8 x_{1,i} \leq 350 \\ similarly  \\ \sum_{i=1}^8 x_{2,i} \leq 185 \\ \sum_{i=1}^8 x_{3,i} \leq 305 \\ \sum_{i=1}^8 x_{4,i} \leq 180 \\ \sum_{i=1}^8 x_{5,i} \leq 205 \\ \sum_{i=1}^8 x_{6,i} \leq 175 \\ \sum_{i=1}^8 x_{7,i} \leq 325 \\ \sum_{i=1}^8 x_{8,i} \leq 370 \\ x_{ij} \geq 0 \ ∀ i,j $
 
 A = 

[[827,817,1470,2272,1615,3143,1264,4465

559,1832,751,3772,637,3773,1856,5459

1109,2443,577,3865,798,3521,1984,5303

2943,1471,4676,1337,2702,2741,2482,4148

3742,3089,2931,3199,2226,1739,1691,2128

2353,1160,3295,368,2369,2365,1293,3642

1356,1617,2045,2941,2334,4151,1937,4287

195,1862,1331,2921,402,2825,563,4441]]


Cost function = $ A_{ij}  * X{ij}  ∀ i,j ∈ {1,2, ⋯8} 
 and X_{ij} = [x_{ij}] $
 
  
Objective function = minimize $ A_{ij}  * X{ij}  ∀ i,j ∈ {1,2, ⋯8} 
 and X_{ij} = [x_{ij}] $ 

  

In [ ]:
data_csvfile = pd.read_csv('lab6_ex1_1.csv')

In [ ]:
data_csvfile.index

RangeIndex(start=0, stop=9, step=1)

RangeIndex(start=0, stop=9, step=1)

In [ ]:
model=ConcreteModel()

In [ ]:
M = len(data_csvfile.index)-1  
print('warehouses: ',M)

warehouses:  8
warehouses:  8


In [ ]:
N = len(data_csvfile.columns)-2 
print('markets: ',N)

markets:  8
markets:  8


In [ ]:
row_indices = range(M)
col_indices = range(N)


In [ ]:
for row_idx in row_indices:
  for col_idx in col_indices:
    print('cost[',row_idx,'][',col_idx+1,']:',data_csvfile.iloc[row_idx, col_idx+1])

cost[ 0 ][ 1 ]: 827
cost[ 0 ][ 2 ]: 817
cost[ 0 ][ 3 ]: 1470
cost[ 0 ][ 4 ]: 2272
cost[ 0 ][ 5 ]: 1615
cost[ 0 ][ 6 ]: 3143
cost[ 0 ][ 7 ]: 1264
cost[ 0 ][ 8 ]: 4465
cost[ 1 ][ 1 ]: 559
cost[ 1 ][ 2 ]: 1832
cost[ 1 ][ 3 ]: 751
cost[ 1 ][ 4 ]: 3772
cost[ 1 ][ 5 ]: 637
cost[ 1 ][ 6 ]: 3773
cost[ 1 ][ 7 ]: 1856
cost[ 1 ][ 8 ]: 5459
cost[ 2 ][ 1 ]: 1109
cost[ 2 ][ 2 ]: 2443
cost[ 2 ][ 3 ]: 577
cost[ 2 ][ 4 ]: 3865
cost[ 2 ][ 5 ]: 798
cost[ 2 ][ 6 ]: 3521
cost[ 2 ][ 7 ]: 1984
cost[ 2 ][ 8 ]: 5303
cost[ 3 ][ 1 ]: 2943
cost[ 3 ][ 2 ]: 1471
cost[ 3 ][ 3 ]: 4676
cost[ 3 ][ 4 ]: 1337
cost[ 3 ][ 5 ]: 2702
cost[ 3 ][ 6 ]: 2741
cost[ 3 ][ 7 ]: 2482
cost[ 3 ][ 8 ]: 4148
cost[ 4 ][ 1 ]: 3742
cost[ 4 ][ 2 ]: 3089
cost[ 4 ][ 3 ]: 2931
cost[ 4 ][ 4 ]: 3199
cost[ 4 ][ 5 ]: 2226
cost[ 4 ][ 6 ]: 1739
cost[ 4 ][ 7 ]: 1691
cost[ 4 ][ 8 ]: 2128
cost[ 5 ][ 1 ]: 2353
cost[ 5 ][ 2 ]: 1160
cost[ 5 ][ 3 ]: 3295
cost[ 5 ][ 4 ]: 368
cost[ 5 ][ 5 ]: 2369
cost[ 5 ][ 6 ]: 2365
cost[ 5 ][ 7 ]: 1293
cost[ 5 ][ 8 ]: 3642


In [ ]:
 model.x=Var(row_indices, col_indices, domain= NonNegativeReals)

In [ ]:
model.objective = Objective(expr=sum(data_csvfile.iloc[i,j+1]*model.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

In [ ]:
model.constraints=ConstraintList()

In [ ]:
for i in range(8):
  model.constraints.add(expr=sum(model.x[i,j] for j in col_indices) <= data_csvfile.iloc[i,N+1]) 

In [ ]:
for j in range(8):
  model.constraints.add(expr=sum(model.x[i,j] for i in row_indices) == data_csvfile.iloc[M,j+1])

In [ ]:
model.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   16 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :   64 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7)}
    x_index_0 : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
    

In [ ]:
!apt-get install -y -qq coinor-cbc

In [ ]:
opt_cbc = SolverFactory('cbc')

In [ ]:
result = opt_cbc.solve(model)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal
Solver status: ok
Solver termination condition: optimal


In [ ]:

print('\nObjective = ', model.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    print('Num EV ',data_csvfile['Warehouses'][i],' and ', data_csvfile.columns[j+1],':', model.x[i,j].value)

print('\nConstraints')
model.constraints.display()
for i in row_indices:
  for j in col_indices:
    if model.x[i,j].value!=0:
      print('Number of truck loads of EV',data_csvfile['Warehouses'][i],'and',data_csvfile.columns[j+1],':',model.x[i,j].value)


Objective =  2192870.0

Decision Variables
Num EV  Ahmedabad  and  Hassan : 0.0
Num EV  Ahmedabad  and  Jodhpur : 300.0
Num EV  Ahmedabad  and  Trichy : 0.0
Num EV  Ahmedabad  and  Simla : 0.0
Num EV  Ahmedabad  and  Vijayawada : 0.0
Num EV  Ahmedabad  and  Dibrugarh : 45.0
Num EV  Ahmedabad  and  Raipur : 5.0
Num EV  Ahmedabad  and  Agartala : 0.0
Num EV  Bengaluru  and  Hassan : 0.0
Num EV  Bengaluru  and  Jodhpur : 0.0
Num EV  Bengaluru  and  Trichy : 120.0
Num EV  Bengaluru  and  Simla : 0.0
Num EV  Bengaluru  and  Vijayawada : 65.0
Num EV  Bengaluru  and  Dibrugarh : 0.0
Num EV  Bengaluru  and  Raipur : 0.0
Num EV  Bengaluru  and  Agartala : 0.0
Num EV  Chennai  and  Hassan : 0.0
Num EV  Chennai  and  Jodhpur : 0.0
Num EV  Chennai  and  Trichy : 305.0
Num EV  Chennai  and  Simla : 0.0
Num EV  Chennai  and  Vijayawada : 0.0
Num EV  Chennai  and  Dibrugarh : 0.0
Num EV  Chennai  and  Raipur : 0.0
Num EV  Chennai  and  Agartala : 0.0
Num EV  Delhi  and  Hassan : 0.0
Num EV  Delhi  a

Answer2:
Number of truck loads of EV Ahmedabad and Jodhpur : 300.0  \\
Number of truck loads of EV Ahmedabad and Dibrugarh : 45.0  \\
Number of truck loads of EV Ahmedabad and Raipur : 5.0 \\
Number of truck loads of EV Bengaluru and Trichy : 120.0 \\
Number of truck loads of EV Bengaluru and Vijayawada : 65.0 \\
Number of truck loads of EV Chennai and Trichy : 305.0 \\
Number of truck loads of EV Delhi and Simla : 95.0 \\
Number of truck loads of EV Delhi and Dibrugarh : 85.0 \\
Number of truck loads of EV Kolkata and Dibrugarh : 95.0 \\
Number of truck loads of EV Kolkata and Agartala : 110.0 \\
Number of truck loads of EV Lucknow and Simla : 175.0 \\
Number of truck loads of EV Mumbai and Hassan : 205.0 \\
Number of truck loads of EV Mumbai and Raipur : 120.0 \\
Number of truck loads of EV Hyderabad and Vijayawada : 310.0 \\
Number of truck loads of EV Hyderabad and Raipur : 60.0 

 Cost of transportation:   2192870.0

Answer3:
Now given that Lucknow to Shimla route is disrupted and no transportation is possible on this route so we can't transport anything on this route so to solve the optimization problem we make the cost of tranportation on route Lucknow-Shimla so larger then the cost of other routes.Since we are to minimize the total cost so if the cost of Lucknow-Shimla route is much larger than others than it will not put any effect in objective function.

So we change the cost of Lucknow-Shimla route to 10000 in .csv file.
now first we deactivate the last objective since cost value puts the effect only in objective function. And we define a new constraint.

In [ ]:
data_csvfile_1 = pd.read_csv('lab6_ex1_2.csv')

In [ ]:
data_csvfile_1.columns

Index(['Warehouses', 'Hassan', 'Jodhpur', 'Trichy', 'Simla', 'Vijayawada',
       'Dibrugarh', 'Raipur', 'Agartala', 'AvailStock'],
      dtype='object')

Index(['Warehouses', 'Hassan', 'Jodhpur', 'Trichy', 'Simla', 'Vijayawada',
       'Dibrugarh', 'Raipur', 'Agartala', 'AvailStock'],
      dtype='object')

In [ ]:
model.objective.deactivate

<bound method ActiveComponentData.deactivate of <pyomo.core.base.objective.ScalarObjective object at 0x7fe055b457c0>>

<bound method ActiveComponentData.deactivate of <pyomo.core.base.objective.ScalarObjective object at 0x7fe055bcd520>>

In [ ]:
model.objective =  Objective(expr=sum(data_csvfile_1.iloc[i,j+1]*model.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

This is usually indicative of a modelling error.
To avoid this warning, use block.del_component() and block.add_component().
This is usually indicative of a modelling error.
To avoid this warning, use block.del_component() and block.add_component().


In [ ]:
model.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   16 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :   64 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7)}
    x_index_0 : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
    

In [ ]:
!apt-get install -y -qq coinor-cbc

In [ ]:
opt_cbc = SolverFactory('cbc')

In [ ]:
result = opt_cbc.solve(model)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal
Solver status: ok
Solver termination condition: optimal


In [ ]:
print('\nObjective = ', model.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    print('Num EV ',data_csvfile_1['Warehouses'][i],' and ', data_csvfile.columns[j+1],':', model.x[i,j].value)

print('\nConstraints')
model.constraints.display()
for i in row_indices:
  for j in col_indices:
    if model.x[i,j].value!=0:
      print('Number of truck loads of EV',data_csvfile_1['Warehouses'][i],'and',data_csvfile_1.columns[j+1],':',model.x[i,j].value)


Objective =  2380570.0

Decision Variables
Num EV  Ahmedabad  and  Hassan : 0.0
Num EV  Ahmedabad  and  Jodhpur : 300.0
Num EV  Ahmedabad  and  Trichy : 0.0
Num EV  Ahmedabad  and  Simla : 0.0
Num EV  Ahmedabad  and  Vijayawada : 0.0
Num EV  Ahmedabad  and  Dibrugarh : 0.0
Num EV  Ahmedabad  and  Raipur : 50.0
Num EV  Ahmedabad  and  Agartala : 0.0
Num EV  Bengaluru  and  Hassan : 0.0
Num EV  Bengaluru  and  Jodhpur : 0.0
Num EV  Bengaluru  and  Trichy : 120.0
Num EV  Bengaluru  and  Simla : 0.0
Num EV  Bengaluru  and  Vijayawada : 65.0
Num EV  Bengaluru  and  Dibrugarh : 0.0
Num EV  Bengaluru  and  Raipur : 0.0
Num EV  Bengaluru  and  Agartala : 0.0
Num EV  Chennai  and  Hassan : 0.0
Num EV  Chennai  and  Jodhpur : 0.0
Num EV  Chennai  and  Trichy : 305.0
Num EV  Chennai  and  Simla : 0.0
Num EV  Chennai  and  Vijayawada : 0.0
Num EV  Chennai  and  Dibrugarh : 0.0
Num EV  Chennai  and  Raipur : 0.0
Num EV  Chennai  and  Agartala : 0.0
Num EV  Delhi  and  Hassan : 0.0
Num EV  Delhi  a

Answer4:
Number of truck loads of EV Ahmedabad and Jodhpur : 300.0  \\
Number of truck loads of EV Ahmedabad and Dibrugarh : 50.0  \\
Number of truck loads of EV Bengaluru and Trichy : 120.0 \\
Number of truck loads of EV Bengaluru and Vijayawada : 65.0    
Number of truck loads of EV Chennai and Trichy : 305.0 \\
Number of truck loads of EV Delhi and Simla : 180.0 \\
Number of truck loads of EV Kolkata and Raipur : 95.0 \\
Number of truck loads of EV Kolkata and Agartala : 110.0 \\
Number of truck loads of EV Lucknow and Dibrugarh : 175.0 \\
Number of truck loads of EV Mumbai and Hassan : 205.0 \\
Number of truck loads of EV Mumbai and Simla : 90.0 \\
Number of truck loads of EV Mumbai and Raipur : 30.0 \\
Number of truck loads of EV Hyderabad and Vijayawada : 310.0 \\
Number of truck loads of EV Hyderabad and Raipur : 60.0 \\
  Total cost is now :   2380570.0

  Part2:
  Here we obsereve that minimum cost of transportation is increased as comparison to last time when transportation on route Lucknow-Shimla was availabe to transport.Since from Lucknow to any other market,cost of transportation is higher than cost of  Lucknow to Shimla route.Here this route is disrupted so cost of transportation will increase to transport by another route.


Answer10:
Now given that routes of Lucknow-Shimla,Kolkata-dilbrugarh and Delhi-Raipur are disrupted. So transportation is not possible on these three routes.Now again we will consider the cost of transportation by these routes is much larger than others.Let's consider cost related to  these routes is 10000.We will change this in .csv file.Since this will put an effect only in objective function.SO we deactivate the last objective function and define a new objective.

In [ ]:
model.objective.deactivate

<bound method ActiveComponentData.deactivate of <pyomo.core.base.objective.ScalarObjective object at 0x7fe055afb520>>

<bound method ActiveComponentData.deactivate of <pyomo.core.base.objective.ScalarObjective object at 0x7fe0552d7d00>>

In [ ]:
data_csvfile_2 = pd.read_csv('lab6_ex1_3.csv')

In [ ]:
data_csvfile_2.index

RangeIndex(start=0, stop=9, step=1)

RangeIndex(start=0, stop=9, step=1)

In [ ]:
model.objective= Objective(expr=sum(data_csvfile_2.iloc[i,j+1]*model.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

This is usually indicative of a modelling error.
To avoid this warning, use block.del_component() and block.add_component().
This is usually indicative of a modelling error.
To avoid this warning, use block.del_component() and block.add_component().


In [ ]:
model.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   16 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :   64 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7)}
    x_index_0 : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
    

In [ ]:
!apt-get install -y -qq coinor-cbc

In [ ]:
opt_cbc = SolverFactory('cbc')

In [ ]:
result = opt_cbc.solve(model)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal
Solver status: ok
Solver termination condition: optimal


In [ ]:
print('\nObjective = ', model.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    print('Number of EV ',data_csvfile_2['Warehouses'][i],' and ', data_csvfile_2.columns[j+1],':', model.x[i,j].value)

print('\nConstraints')
model.constraints.display()
for i in row_indices:
  for j in col_indices:
    if model.x[i,j].value!=0:
      print('Number of truck loads of EV',data_csvfile_2['Warehouses'][i],'and',data_csvfile_2.columns[j+1],':',model.x[i,j].value)


Objective =  2518200.0

Decision Variables
Number of EV  Ahmedabad  and  Hassan : 0.0
Number of EV  Ahmedabad  and  Jodhpur : 300.0
Number of EV  Ahmedabad  and  Trichy : 0.0
Number of EV  Ahmedabad  and  Simla : 0.0
Number of EV  Ahmedabad  and  Vijayawada : 0.0
Number of EV  Ahmedabad  and  Dibrugarh : 50.0
Number of EV  Ahmedabad  and  Raipur : 0.0
Number of EV  Ahmedabad  and  Agartala : 0.0
Number of EV  Bengaluru  and  Hassan : 0.0
Number of EV  Bengaluru  and  Jodhpur : 0.0
Number of EV  Bengaluru  and  Trichy : 120.0
Number of EV  Bengaluru  and  Simla : 0.0
Number of EV  Bengaluru  and  Vijayawada : 65.0
Number of EV  Bengaluru  and  Dibrugarh : 0.0
Number of EV  Bengaluru  and  Raipur : 0.0
Number of EV  Bengaluru  and  Agartala : 0.0
Number of EV  Chennai  and  Hassan : 0.0
Number of EV  Chennai  and  Jodhpur : 0.0
Number of EV  Chennai  and  Trichy : 305.0
Number of EV  Chennai  and  Simla : 0.0
Number of EV  Chennai  and  Vijayawada : 0.0
Number of EV  Chennai  and  Dibru

Answer11:
* Number of truck loads of EV Ahmedabad and Jodhpur:300.0 \\
* Number of truck loads of EV Ahmedabad and Dibrugarh : 50.0 \\
* Number of truck loads of EV Bengaluru and Trichy : 120.0 \\
*Number of truck loads of EV Bengaluru and Vijayawada : 65.0 \\
*Number of truck loads of EV Chennai and Trichy : 305.0 \\
* Number of truck loads of EV Delhi and Simla : 180.0 \\
* * Number of truck loads of EV Kolkata and Raipur : 95.0 \\
* Number of truck loads of EV Kolkata and Agartala : 110.0 \\
* Number of truck loads of EV Lucknow and Dibrugarh : 175.0 \\
* Number of truck loads of EV Mumbai and Hassan : 205.0 \\
* Number of truck loads of EV Mumbai and Simla : 90.0 \\
*Number of truck loads of EV Mumbai and Raipur : 30.0 \\
* Number of truck loads of EV Hyderabad and Vijayawada : 310.0 \\
* Number of truck loads of EV Hyderabad and Raipur : 60.0 \\

* minimum transportaion: 2518200.0
* Part2:
Here we observe that minimum transportation cost is increased in comparison of last two cases when we blocked two routes.Since the new two routes which are blocked Delhi-Raipur and Kolkata-dilbrugarh are one of these routes which have low cost than most of the routes.So Cost increases.